###
/main.do

### 문자열 반환
GET http://localhost:8080/api/noticeInput

<> 2023-04-25T101849.200.txt

### 값 반환
GET http://localhost:8080/api/noticeInput2
Content-Type: application/json; charset=UTF-8

<> 2023-04-25T105820.200.txt
<> 2023-04-25T105049.200.txt
<> 2023-04-25T104949.200.txt

### 리스트 반환(빌더의 활용)
GET http://localhost:8080/api/notice3

### Null 생성
GET http://localhost:8080/api/notice4

### 게시글 개수 세기
GET http://localhost:8080/api/count


### 게시글 제목과 내용 더하기 ex_11
POST http://localhost:8080/api/noticeInput/
Content-Type: application/x-www-form-urlencoded

title=제목1&description=내용1

### 게시글 입력 추상 형태 ex_12
POST http://localhost:8080/api/noticeInput2
Content-Type: application/x-www-form-urlencoded

title=제목1&description=내용1

### 게시글 입력 show json type ex_13
POST http://localhost:8080/api/notice3
Content-Type: application/json

{
"title" : "새로운 제목",
"description" : "새로운 내용"
}

### 실제 db로 값 설정해 확인 ex_14
POST http://localhost:8080/api/notice4
Content-Type: application/json

{
  "title" : "더 새로운 제목",
  "description" : "더 새로운 내용"
}

### 조회수 좋아요 0부터 시작 ex_15
POST http://localhost:8080/api/notice5
Content-Type: application/json

{
  "title" : "더 새로운 제목",
  "description" : "더 새로운 내용"
}

### notice가 존재하면 헤당 id를 없으면 null을 반환 ex_16
GET http://localhost:8080/api/notice/5

### 업데이트 ex_17
PUT http://localhost:8080/api/notice/5
Content-Type: application/json

{
  "title" : "더 새로운 제목",
  "description" : "더 새로운 내용"
}

### 에러를 다루어 보자 ex_18
PUT http://localhost:8080/api/noticeError/2
Content-Type: application/json

{
  "title" : "더 새로운 제목",
  "description" : "더 새로운 내용"
}

### ex 19 날짜까지 변경
PUT http://localhost:8080/api/noticeDate/1
Content-Type: application/json

{
  "title" : "더 새로운 제목",
  "description" : "더 새로운 내용"
}

### ex 20 조회수 수정을 위한 Patch 활용
PATCH http://localhost:8080/api/noticePatch/1

### ex_21 DeleteMapping 통한 삭제만 구현.
DELETE http://localhost:8080/api/noticeDelete/3

### ex_22 DeleteMapping 통한 삭제와 예외 구현.
DELETE http://localhost:8080/api/noticeDeleteThrow/1